spring:
  kafka:
    bootstrap-servers: 192.168.200.11:9092
    # 生产者配置
    producer:
      clientId: ${spring.application.name} #方便kafkaserver打印日志定位请求来源
      # 序列化key的类
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 反序列化value的类
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # 发生错误后，消息重发的次数 ，0为不启用重试机制，默认int最大值
      retries: 1
    #消费者的配置
    consumer:
      # 反序列化key的类
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 反序列化value的类
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #在/usr/local/etc/kafka/consumer.properties中有配置
      group-id: test_group
      auto-offset-reset: earliest
      # 表示接受反序列化任意的类，也可限定包路径
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    listener:
      idle-event-interval: 5000